begin;
create extension if not exists pgtap with schema extensions;
select plan(1);
create temporary table test_ids as select gen_random_uuid() as owner_id,gen_random_uuid() as editor_id,gen_random_uuid() as outsider_id,gen_random_uuid() as site_id,gen_random_uuid() as other_site_id,gen_random_uuid() as asset_id,gen_random_uuid() as metadata_asset_id;
grant select on test_ids to service_role;
insert into auth.users(id,aud,role,email,created_at,updated_at) select owner_id,'authenticated','authenticated','owner-test@example.invalid',now(),now() from test_ids union all select editor_id,'authenticated','authenticated','editor-test@example.invalid',now(),now() from test_ids union all select outsider_id,'authenticated','authenticated','outsider-test@example.invalid',now(),now() from test_ids;
insert into app_private.sites(id,slug,name) select site_id,'test-'||site_id,'Test' from test_ids union all select other_site_id,'test-'||other_site_id,'Other' from test_ids;
insert into app_private.site_memberships(site_id,user_id,role) select site_id,owner_id,'owner' from test_ids union all select site_id,editor_id,'editor' from test_ids;
insert into app_private.media_assets(id,site_id,owner_id,kind,bucket,object_path,state,metadata) select asset_id,site_id,owner_id,'image','published-media',asset_id::text,'ready','{"mime":"image/png","bytes":100,"width":10,"height":10}'::jsonb from test_ids union all select metadata_asset_id,site_id,owner_id,'image','published-media',metadata_asset_id::text,'ready','{"mime":"image/png","bytes":100,"width":10,"height":10}'::jsonb from test_ids;
set local role service_role;
do $$
declare t record; r jsonb; pid uuid; base_pid uuid; cid uuid; guest_reply_id uuid; member_reply_id uuid; ver int; rid uuid; req uuid:=gen_random_uuid(); d jsonb; base_d jsonb; meta_case record; hash text:='$argon2id$v=19$m=19456,t=2,p=1$example$example';
begin
 select * into t from test_ids;
 r:=public.travel_api('site.get',null,jsonb_build_object('site_id',t.site_id)); assert r->>'name'='Test';
 r:=public.travel_api('me',t.owner_id,'{}'); assert jsonb_array_length(r->'memberships')=1;
 r:=public.travel_account_delete_request(t.outsider_id); assert (r->>'requested')::boolean;
 d:=public.travel_account_delete_request(t.outsider_id); assert d->>'request_id'=r->>'request_id';
 r:=public.travel_admin_account_deletions(t.owner_id,t.site_id); assert jsonb_array_length(r)=1;
 r:=public.travel_admin_account_deletion_anonymize(t.owner_id,t.site_id,(d->>'request_id')::uuid); assert r->>'status'='anonymized';
 begin perform public.travel_admin_account_deletion_complete(t.owner_id,t.site_id,(d->>'request_id')::uuid); raise exception 'auth deletion skipped'; exception when sqlstate 'PT409' then null; end;
 r:=public.travel_admin_comments(t.owner_id,t.site_id,50,0); assert jsonb_typeof(r)='array';
 r:=public.travel_admin_comment_inbox(t.owner_id,t.site_id,'all',50,0); assert r='[]'::jsonb;
 begin perform public.travel_admin_comment_inbox(t.owner_id,t.site_id,'invalid',50,0); raise exception 'invalid inbox filter accepted'; exception when sqlstate 'PT422' then null; end;
 begin perform public.travel_admin_comment_inbox(t.outsider_id,t.site_id,'all',50,0); raise exception 'outsider read inbox'; exception when sqlstate 'PT403' then null; end;
 perform public.travel_api('profile.save',t.owner_id,'{"display_name":"테스트"}');
 begin perform public.travel_api('admin.post.create',t.outsider_id,jsonb_build_object('site_id',t.site_id,'kind','article')); raise exception 'cross-site authorization failed'; exception when sqlstate 'PT403' then null; end;
 r:=public.travel_api('admin.post.create',t.editor_id,jsonb_build_object('site_id',t.site_id,'kind','article')); pid:=(r->>'id')::uuid;
 begin perform public.travel_api('admin.post.publish',t.outsider_id,jsonb_build_object('id',pid,'version',0)); raise exception 'outsider publish allowed'; exception when sqlstate 'PT403' then null; end;
 begin perform public.travel_api('admin.post.status',t.outsider_id,jsonb_build_object('id',pid,'version',0,'status','trashed')); raise exception 'outsider status change allowed'; exception when sqlstate 'PT403' then null; end;
 d:=jsonb_build_object('title','테스트 글','slug','test-post','category_code','day-walk','tags',jsonb_build_array('서울'),'blocks',jsonb_build_array(jsonb_build_object('type','paragraph','content','hello')),'metadata',jsonb_build_object('region','서울','visited_on','2026-09-18'),'cover_asset_id',t.asset_id);
 base_pid:=pid; base_d:=d;
 r:=public.travel_api('admin.post.save',t.editor_id,jsonb_build_object('id',pid,'version',0,'content',d,'checkpoint',true)); assert (r->>'lock_version')::int=1;
 r:=public.travel_admin_posts(t.editor_id,jsonb_build_object('site_id',t.site_id,'category','day-walk','status','draft','search','테스트')); assert jsonb_array_length(r)=1 and r->0->>'category_code'='day-walk';
 r:=public.travel_admin_posts(t.editor_id,jsonb_build_object('site_id',t.site_id,'category','food-cafe')); assert jsonb_array_length(r)=0;
 begin perform public.travel_admin_posts(t.outsider_id,jsonb_build_object('site_id',t.site_id)); raise exception 'admin listing authorization failed'; exception when sqlstate 'PT403' then null; end;
 begin perform public.travel_api('admin.post.save',t.editor_id,jsonb_build_object('id',pid,'version',0,'content',d)); raise exception 'lost update allowed'; exception when sqlstate 'PT409' then null; end;
 r:=public.travel_api('posts.list',null,jsonb_build_object('site_id',t.site_id)); assert jsonb_array_length(r)=0;
 r:=public.travel_api('admin.post.publish',t.editor_id,jsonb_build_object('id',pid,'version',1,'rendered_html','<p>hello</p>','asset_ids','[]'::jsonb)); rid:=(r->>'revision_id')::uuid;
 r:=public.travel_api('post.get',null,jsonb_build_object('site_id',t.site_id,'id',pid)); assert r->>'title'='테스트 글';
 r:=public.travel_api('posts.list',null,jsonb_build_object('site_id',t.site_id)); assert jsonb_array_length(r)=1;
 for meta_case in select * from (values
  ('day-walk','{"region":"서울","visited_on":"2026-09-18"}'::jsonb,'{"region":"서울","visited_on":"2026-02-30"}'::jsonb,'invalid_date'),
  ('overnight-trip','{"region":"제주","start_date":"2026-09-18","end_date":"2026-09-20"}'::jsonb,'{"region":"제주","start_date":"2026-09-20","end_date":"2026-09-18"}'::jsonb,'invalid_dates'),
  ('food-cafe','{"region":"강릉","visited_on":"2026-09-18","place_name":"바다 카페","venue_type":"cafe"}'::jsonb,'{"region":"강릉","visited_on":"2026-09-18","place_name":"바다 카페","venue_type":"bar"}'::jsonb,'invalid_venue'),
  ('stay-review','{"region":"제주","check_in":"2026-09-18","check_out":"2026-09-20","place_name":"바다 숙소"}'::jsonb,'{"region":"제주","check_in":"2026-09-18","check_out":"2026-09-20"}'::jsonb,'missing_place')
 ) as metadata_cases(category,valid_metadata,invalid_metadata,expected_error) loop
  d:=jsonb_build_object('title','메타데이터 검증','slug','metadata-'||meta_case.category,'category_code',meta_case.category,'cover_asset_id',t.metadata_asset_id,'blocks',jsonb_build_array(jsonb_build_object('type','paragraph','content','검증 본문')),'metadata',meta_case.invalid_metadata);
  r:=public.travel_api('admin.post.create',t.editor_id,jsonb_build_object('site_id',t.site_id,'kind','article','content',d)); pid:=(r->>'id')::uuid;
  begin
   perform public.travel_api('admin.post.publish',t.editor_id,jsonb_build_object('id',pid,'version',0,'rendered_html','<p>검증 본문</p>','asset_ids','[]'::jsonb));
   raise exception 'invalid category metadata accepted: %',meta_case.category;
  exception
   when sqlstate '22007' or sqlstate '22008' then assert meta_case.expected_error='invalid_date';
   when sqlstate 'PT422' then assert sqlerrm=meta_case.expected_error;
  end;
  d:=jsonb_set(d,'{metadata}',meta_case.valid_metadata);
  r:=public.travel_api('admin.post.save',t.editor_id,jsonb_build_object('id',pid,'version',0,'content',d));
  r:=public.travel_api('admin.post.publish',t.editor_id,jsonb_build_object('id',pid,'version',1,'rendered_html','<p>검증 본문</p>','asset_ids','[]'::jsonb));
 end loop;
 r:=public.travel_api('admin.post.save',t.editor_id,jsonb_build_object('id',base_pid,'version',2,'content',base_d||'{"title":"아직 비공개 수정"}'::jsonb));
 r:=public.travel_api('post.get',null,jsonb_build_object('site_id',t.site_id,'slug','test-post')); assert r->>'title'='테스트 글';
 r:=public.travel_api('comment.create',null,jsonb_build_object('id',base_pid,'body','댓글','guest_name','방문자','password_hash',hash,'actor_hash',repeat('a',64),'request_hash','abc','request_key',req)); cid:=(r->>'id')::uuid;
 r:=public.travel_admin_comment_inbox(t.owner_id,t.site_id,'unanswered',50,0); assert jsonb_array_length(r)=1 and r->0->>'id'=cid::text and (r->0->>'comments_enabled')::boolean and r->0->'open_reports'='[]'::jsonb;
 r:=public.travel_api('comment.create',null,jsonb_build_object('id',base_pid,'body','댓글','guest_name','방문자','password_hash',hash,'actor_hash',repeat('a',64),'request_hash','abc','request_key',req)); assert (r->>'duplicate')::boolean;
 r:=public.travel_api('comments.list',null,jsonb_build_object('id',base_pid)); assert jsonb_array_length(r)=1; assert not (r->0 ? 'request_hash');
 begin perform public.travel_api('comment.edit',t.outsider_id,jsonb_build_object('id',cid,'version',0,'body','bad')); raise exception 'comment hijack allowed'; exception when sqlstate 'PT403' then null; end;
 begin perform public.travel_api('comment.edit',null,jsonb_build_object('id',cid,'version',0,'body','비밀번호 없는 수정','guest_verified',false)); raise exception 'guest password bypass allowed'; exception when sqlstate 'PT403' then null; end;
 r:=public.travel_api('comment.edit',null,jsonb_build_object('id',cid,'version',0,'body','수정','guest_verified',true)); assert (r->>'version')::int=1;
 r:=public.travel_api('comment.create',t.outsider_id,jsonb_build_object('id',base_pid,'body','회원 답글','parent_id',cid,'request_hash','member-reply','request_key',gen_random_uuid())); member_reply_id:=(r->>'id')::uuid;
 r:=public.travel_admin_comment_inbox(t.owner_id,t.site_id,'unanswered',50,0); assert jsonb_array_length(r)=1 and r->0->>'id'=cid::text;
 r:=public.travel_api('comments.list',t.outsider_id,jsonb_build_object('id',base_pid));
 select value into d from jsonb_array_elements(r) value where value->>'id'=member_reply_id::text;
 assert (d->>'can_manage')::boolean and not (d->>'is_guest')::boolean;
 r:=public.travel_api('comments.list',null,jsonb_build_object('id',base_pid));
 select value into d from jsonb_array_elements(r) value where value->>'id'=member_reply_id::text;
 assert not (d->>'can_manage')::boolean;
 begin perform public.travel_api('comment.delete',t.owner_id,jsonb_build_object('id',member_reply_id,'version',0)); raise exception 'other account deleted member reply'; exception when sqlstate 'PT403' then null; end;
 r:=public.travel_api('comment.delete',t.outsider_id,jsonb_build_object('id',member_reply_id,'version',0)); assert (r->>'version')::int=1;
 r:=public.travel_api('comment.create',null,jsonb_build_object('id',base_pid,'body','비회원 답글','parent_id',cid,'guest_name','방문자','password_hash',hash,'actor_hash',repeat('b',64),'request_hash','guest-reply','request_key',gen_random_uuid())); guest_reply_id:=(r->>'id')::uuid;
 r:=public.travel_api('comments.list',t.outsider_id,jsonb_build_object('id',base_pid));
 select value into d from jsonb_array_elements(r) value where value->>'id'=guest_reply_id::text;
 assert not (d->>'can_manage')::boolean and (d->>'is_guest')::boolean;
 begin perform public.travel_api('comment.delete',t.outsider_id,jsonb_build_object('id',guest_reply_id,'version',0)); raise exception 'guest reply deleted without password verification'; exception when sqlstate 'PT403' then null; end;
 r:=public.travel_api('comment.delete',t.outsider_id,jsonb_build_object('id',guest_reply_id,'version',0,'guest_verified',true)); assert (r->>'version')::int=1;
 r:=public.travel_api('comment.report',t.outsider_id,jsonb_build_object('id',cid,'reason','spam'));
 r:=public.travel_admin_comment_inbox(t.owner_id,t.site_id,'reported',50,0); assert jsonb_array_length(r)=1 and r->0->>'id'=cid::text and jsonb_array_length(r->0->'open_reports')=1;
 r:=public.travel_api('admin.reports',t.owner_id,jsonb_build_object('site_id',t.site_id)); assert jsonb_array_length(r)=1;
 perform public.travel_api('admin.report.resolve',t.owner_id,jsonb_build_object('site_id',t.site_id,'id',r->0->>'id','status','resolved'));
 r:=public.travel_admin_comment_inbox(t.owner_id,t.site_id,'reported',50,0); assert r='[]'::jsonb;
 perform public.travel_api('comment.create',t.owner_id,jsonb_build_object('id',base_pid,'body','관리자 답글','parent_id',cid,'request_hash','staff-reply','request_key',gen_random_uuid()));
 r:=public.travel_admin_comment_inbox(t.owner_id,t.site_id,'unanswered',50,0); assert r='[]'::jsonb;
 r:=public.travel_api('like.set',t.outsider_id,jsonb_build_object('id',base_pid,'liked',true)); assert (r->>'count')::int=1;
 r:=public.travel_like_get(base_pid,t.outsider_id,null); assert (r->>'liked')::boolean and (r->>'count')::int=1;
 r:=public.travel_api('like.set',t.outsider_id,jsonb_build_object('id',base_pid,'liked',true)); assert (r->>'count')::int=1;
 r:=public.travel_api('like.set',t.outsider_id,jsonb_build_object('id',base_pid,'liked',false)); assert (r->>'count')::int=0;
 begin perform public.travel_api('admin.member.set',t.editor_id,jsonb_build_object('site_id',t.site_id,'user_id',t.editor_id,'role','owner')); raise exception 'self escalation allowed'; exception when sqlstate 'PT403' then null; end;
 begin perform public.travel_api('admin.member.set',t.owner_id,jsonb_build_object('site_id',t.site_id,'user_id',t.owner_id,'role','editor')); raise exception 'last owner removal allowed'; exception when sqlstate 'PT409' then null; end;
 r:=public.travel_api('admin.settings.save',t.owner_id,jsonb_build_object('site_id',t.site_id,'version',0,'settings',jsonb_build_object('template_id','A')));
 r:=public.travel_api('site.get',null,jsonb_build_object('site_id',t.site_id)); assert r->'settings'->>'template_id'='D';
 perform public.travel_api('admin.settings.apply',t.owner_id,jsonb_build_object('site_id',t.site_id,'version',1));
 r:=public.travel_api('site.get',null,jsonb_build_object('site_id',t.site_id)); assert r->'settings'->>'template_id'='A';
 r:=public.travel_api('asset.access',null,jsonb_build_object('id',t.asset_id)); assert r->>'state'='ready';
 r:=public.travel_api('admin.post.status',t.editor_id,jsonb_build_object('id',base_pid,'version',3,'status','private'));
 begin perform public.travel_api('post.get',null,jsonb_build_object('site_id',t.site_id,'id',base_pid)); raise exception 'private leaked'; exception when sqlstate 'PT404' then null; end;
 begin perform public.travel_api('asset.access',null,jsonb_build_object('id',t.asset_id)); raise exception 'private asset leaked'; exception when sqlstate 'PT401' then null; end;
 -- Draft edits remain private; checkpoints, restores and publication updates keep distinct snapshots.
 d:=jsonb_build_object('title','이력 원본','slug','revision-workflow','category_code','day-walk',
  'tags',jsonb_build_array('서울'),'blocks',jsonb_build_array(jsonb_build_object('type','paragraph','content','원본 본문')),
  'metadata',jsonb_build_object('region','서울','visited_on','2026-09-18'),'cover_asset_id',t.asset_id);
 r:=public.travel_api('admin.post.create',t.editor_id,jsonb_build_object('site_id',t.site_id,'kind','article','content',d)); pid:=(r->>'id')::uuid;
 r:=public.travel_api('admin.post.published',t.editor_id,jsonb_build_object('id',pid)); assert r is null;
 r:=public.travel_api('admin.post.publish',t.editor_id,jsonb_build_object('id',pid,'version',0,'rendered_html','<p>원본 본문</p>','asset_ids','[]'::jsonb)); rid:=(r->>'revision_id')::uuid;
 d:=jsonb_set(d,'{title}','"보관할 초안"'::jsonb);
 r:=public.travel_api('admin.post.save',t.editor_id,jsonb_build_object('id',pid,'version',1,'content',d,'checkpoint',true)); assert (r->>'lock_version')::int=2;
 r:=public.travel_api('post.get',null,jsonb_build_object('site_id',t.site_id,'id',pid)); assert r->>'title'='이력 원본';
 r:=public.travel_api('admin.post.published',t.editor_id,jsonb_build_object('id',pid)); assert r->>'revision_id'=rid::text and r->'snapshot'->>'title'='이력 원본';
 r:=public.travel_api('admin.post.save',t.editor_id,jsonb_build_object('id',pid,'version',2,'content',d,'checkpoint',true)); assert (r->>'lock_version')::int=3;
 r:=public.travel_api('admin.revisions',t.editor_id,jsonb_build_object('id',pid)); assert jsonb_array_length(r)=2;
 select id into cid from app_private.post_revisions where post_id=pid and reason='checkpoint';
 r:=public.travel_api('admin.revision.get',t.editor_id,jsonb_build_object('id',pid,'revision_id',cid)); assert r->>'title'='보관할 초안' and r->>'reason'='checkpoint';
 begin perform public.travel_api('admin.revision.delete',t.editor_id,jsonb_build_object('id',pid,'revision_id',rid,'version',3)); raise exception 'active publication deleted'; exception when sqlstate 'PT409' then assert sqlerrm='published_revision_protected'; end;
 begin perform public.travel_api('admin.revision.delete',t.editor_id,jsonb_build_object('id',pid,'revision_id',cid,'version',2)); raise exception 'stale delete allowed'; exception when sqlstate 'PT409' then assert sqlerrm='version_conflict'; end;
 d:=jsonb_set(d,'{title}','"복원 전 초안"'::jsonb);
 r:=public.travel_api('admin.post.save',t.editor_id,jsonb_build_object('id',pid,'version',3,'content',d));
 r:=public.travel_api('admin.revision.restore',t.editor_id,jsonb_build_object('id',pid,'version',4,'revision_id',rid)); assert r->'draft_content'->>'title'='이력 원본';
 assert exists(select 1 from app_private.post_revisions where post_id=pid and reason='before_restore' and snapshot->>'title'='복원 전 초안');
 r:=public.travel_api('admin.revision.delete',t.editor_id,jsonb_build_object('id',pid,'revision_id',cid,'version',5)); assert (r->>'deleted')::boolean;
 assert not exists(select 1 from app_private.post_revisions where id=cid);
 d:=jsonb_set(d,'{title}','"최종 공개"'::jsonb);
 r:=public.travel_api('admin.post.save',t.editor_id,jsonb_build_object('id',pid,'version',5,'content',d));
 r:=public.travel_api('post.get',null,jsonb_build_object('site_id',t.site_id,'id',pid)); assert r->>'title'='이력 원본';
 r:=public.travel_api('admin.post.publish',t.editor_id,jsonb_build_object('id',pid,'version',6,'rendered_html','<p>최종 공개</p>','asset_ids','[]'::jsonb)); assert (r->>'version')::int=7;
 r:=public.travel_api('admin.revision.delete',t.editor_id,jsonb_build_object('id',pid,'revision_id',rid,'version',7)); assert (r->>'deleted')::boolean;
 assert not exists(select 1 from app_private.post_revisions where id=rid);
 r:=public.travel_api('post.get',null,jsonb_build_object('site_id',t.site_id,'id',pid)); assert r->>'title'='최종 공개';
 select count(*) into ver from app_private.post_revisions where post_id=pid;
 r:=public.travel_api('admin.post.publish',t.editor_id,jsonb_build_object('id',pid,'version',7,'rendered_html','<p>최종 공개</p>','asset_ids','[]'::jsonb)); assert (r->>'version')::int=8;
 assert (select count(*) from app_private.post_revisions where post_id=pid)=ver;
 assert app_private.revision_excerpt('{"blocks":[{"type":"heading","content":[{"type":"text","text":"test 안녕"}]},{"type":"paragraph","content":[{"type":"text","text":"수정된 본문"}]},{"type":"image","props":{}},{"type":"image","props":{}}]}'::jsonb)='수정된 본문 · 사진 2장';
 r:=public.travel_api('rate.consume',null,'{"key_hash":"test","action":"test","window_seconds":60,"max":1}'); assert (r->>'allowed')::boolean;
 r:=public.travel_api('rate.consume',null,'{"key_hash":"test","action":"test","window_seconds":60,"max":1}'); assert not (r->>'allowed')::boolean;
 raise notice 'API integration assertions passed';
end $$;
set local role anon;
do $$ begin
 begin perform public.travel_api('site.get',null,'{}'); raise exception 'RPC exposed'; exception when insufficient_privilege then null; end;
 begin perform public.travel_like_get(gen_random_uuid(),null,repeat('a',64)); raise exception 'like lookup RPC exposed'; exception when insufficient_privilege then null; end;
 begin perform public.travel_admin_posts(gen_random_uuid(),'{}'); raise exception 'admin listing RPC exposed'; exception when insufficient_privilege then null; end;
 begin perform public.travel_admin_comments(gen_random_uuid(),gen_random_uuid(),50,0); raise exception 'admin comments RPC exposed'; exception when insufficient_privilege then null; end;
 begin perform public.travel_admin_comment_inbox(gen_random_uuid(),gen_random_uuid(),'all',50,0); raise exception 'filtered inbox RPC exposed'; exception when insufficient_privilege then null; end;
 begin perform public.travel_account_delete_request(gen_random_uuid()); raise exception 'account request RPC exposed'; exception when insufficient_privilege then null; end;
 begin perform public.travel_admin_account_deletions(gen_random_uuid(),gen_random_uuid()); raise exception 'account queue RPC exposed'; exception when insufficient_privilege then null; end;
 begin perform 1 from public.comments; raise exception 'comments exposed'; exception when insufficient_privilege then null; end;
 begin perform 1 from app_private.posts; raise exception 'drafts exposed'; exception when insufficient_privilege then null; end;
end $$;
reset role;
select pass('API integration assertions passed');
select * from finish();
rollback;
