import { NextResponse, type NextRequest } from "next/server";
import { refreshSession } from "@repo/database/proxy";
// Mirage cannot intercept server requests. Skip session refresh in offline mock mode;
// protected server routes still perform their real authorization checks.
export async function proxy(request: NextRequest) {
  // Replace any caller-supplied value with a request ID generated by this app.
  const requestId = crypto.randomUUID();
  if (
    process.env.NODE_ENV === "development" &&
    process.env.NEXT_PUBLIC_API_MOCKING === "enabled"
  ) {
    const headers = new Headers(request.headers);
    headers.set("x-travel-request-id", requestId);
    const response = NextResponse.next({ request: { headers } });
    response.headers.set("X-Travel-Request-Id", requestId);
    return response;
  }
  const response = await refreshSession(request, requestId);
  response.headers.set("X-Travel-Request-Id", requestId);
  return response;
}
export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",
  ],
};
