-- Preserve the separately stored public publication while retaining distinct editor snapshots.
alter table app_private.post_revisions
 add column reason text not null default 'checkpoint' check(reason in ('checkpoint','published','before_restore')),
 add column post_version integer check(post_version>=0),
 add column revision_order bigint generated by default as identity;
create index revisions_order_idx on app_private.post_revisions(post_id,revision_order desc);
grant usage on sequence app_private.post_revisions_revision_order_seq to service_role;
update app_private.post_revisions pr set reason='published'
where exists(select 1 from public.post_publications pu where pu.revision_id=pr.id)
 or exists(select 1 from app_private.audit_events ae
  where ae.action='post.publish' and ae.changes->>'revision_id'=pr.id::text);

create or replace function app_private.revision_excerpt(p_snapshot jsonb) returns text
language sql immutable set search_path='' as $$
 select left(coalesce(
  nullif(p_snapshot#>>'{blocks,0,content,0,text}',''),
  case when jsonb_typeof(p_snapshot#>'{blocks,0,content}')='string'
   then nullif(p_snapshot#>>'{blocks,0,content}','') end,
  nullif(p_snapshot->>'summary',''),
  (select '사진 '||count(*)::text||'장' from jsonb_array_elements(
   case when jsonb_typeof(p_snapshot->'blocks')='array'
    then p_snapshot->'blocks' else '[]'::jsonb end) b
   where b->>'type'='image' having count(*)>0),''),140)
$$;
revoke all on function app_private.revision_excerpt(jsonb) from public,anon,authenticated;
grant execute on function app_private.revision_excerpt(jsonb) to service_role;

create or replace function public.travel_api(p_action text,p_actor uuid default null,p_input jsonb default '{}') returns jsonb
language plpgsql security invoker set search_path='' as $$
#variable_conflict use_column
declare
 s uuid:=nullif(p_input->>'site_id','')::uuid; v_id uuid:=nullif(p_input->>'id','')::uuid;
 p app_private.posts; c public.comments; a app_private.media_assets; st app_private.sites; r app_private.post_revisions; u public.post_publications;
 d jsonb; res jsonb; rev uuid; aid uuid; key text; n int; v int; role_name text; target uuid; b boolean;
 lim int:=least(greatest(coalesce((p_input->>'limit')::int,12),1),50);
 offst int:=least(greatest(coalesce((p_input->>'offset')::int,0),0),100000);
 actorhash text:=p_input->>'actor_hash'; win timestamptz;
begin
 if p_input is null or jsonb_typeof(p_input)<>'object' then raise exception 'invalid_input' using errcode='PT400'; end if;
 if p_actor is not null and not app_private.is_active_user(p_actor) then raise exception 'unauthorized' using errcode='PT401'; end if;
 if p_action='rate.consume' then
 n:=greatest(1,least((p_input->>'window_seconds')::int,86400));
 win:=to_timestamp(floor(extract(epoch from now())/n)*n);
 insert into app_private.rate_limits(key_hash,action,window_start,count) values(p_input->>'key_hash',p_input->>'action',win,1)
 on conflict(key_hash,action,window_start) do update set count=app_private.rate_limits.count+1 returning count into v;
 return jsonb_build_object('allowed',v<=(p_input->>'max')::int,'retry_after',n);
 elsif p_action='site.get' then
 select * into st from app_private.sites where status='active' and (id=s or (s is null and slug=coalesce(p_input->>'slug','parents-travel')));
 if not found then raise exception 'not_found' using errcode='PT404'; end if;
 return jsonb_build_object('id',st.id,'slug',st.slug,'name',st.name,'settings',st.published_settings,'version',st.settings_version);
 elsif p_action='posts.list' then
 return coalesce((select jsonb_agg(x) from (select u.post_id,u.slug,u.title,u.category_code,u.tags,u.metadata,u.cover_asset_id,u.pdf_asset_id,u.published_at,u.updated_at,
 case when p.kind='article' then (select count(*) from app_private.post_likes l where l.post_id=u.post_id) end as like_count,
 case when p.kind='article' then (select count(*) from public.comments c where c.post_id=u.post_id and c.status='visible') end as comment_count
 from public.post_publications u join app_private.posts p on p.id=u.post_id where u.site_id=s and app_private.is_public(u.post_id)
 and (p_input->>'category' is null or u.category_code=p_input->>'category') and (p_input->>'tag' is null or p_input->>'tag'=any(u.tags))
 order by u.published_at desc,u.post_id limit lim offset offst) x),'[]');
 elsif p_action='post.get' then
 select * into p from app_private.posts where app_private.posts.id=(select u.post_id from public.post_publications u where u.site_id=s and (u.post_id=v_id or (v_id is null and u.slug=p_input->>'slug')));
 if p.id is null or not app_private.is_public(p.id) then raise exception 'not_found' using errcode='PT404'; end if;
 return (select to_jsonb(u)-'revision_id'-'withdrawn_at' from public.post_publications u where post_id=p.id) || jsonb_build_object('like_count',case when p.kind='article' then (select count(*) from app_private.post_likes where post_id=p.id) end,'comment_count',case when p.kind='article' then (select count(*) from public.comments where post_id=p.id and status='visible') end);
 elsif p_action='comments.list' then
 if not app_private.is_public(v_id) then raise exception 'not_found' using errcode='PT404'; end if;
 return coalesce((select jsonb_agg(x) from (select c.id,c.parent_id,case when c.status='deleted' then '' else c.body end as body,c.status,c.version,c.created_at,c.updated_at,
 case when c.status='deleted' or c.author_kind='anonymized' then '삭제된 사용자' else coalesce(pr.display_name,c.guest_name,'독자') end as display_name,
 exists(select 1 from app_private.site_memberships m join app_private.posts p on p.site_id=m.site_id where p.id=c.post_id and m.user_id=c.author_id and m.active) as is_staff,
 (c.status='visible' and c.author_kind='member' and p_actor is not null and c.author_id=p_actor) as can_manage,
 (c.status='visible' and c.author_kind='guest') as is_guest
 from public.comments c left join public.profiles pr on pr.user_id=c.author_id where c.post_id=v_id and (c.status='visible' or (c.status='deleted' and exists(select 1 from public.comments r where r.parent_id=c.id and r.status='visible')))
 order by c.created_at,c.id limit lim offset offst) x),'[]');
 elsif p_action='me' then
 if p_actor is null then raise exception 'unauthorized' using errcode='PT401'; end if;
 return jsonb_build_object('user_id',p_actor,'profile',(select to_jsonb(pr) from public.profiles pr where user_id=p_actor),'memberships',coalesce((select jsonb_agg(jsonb_build_object('site_id',m.site_id,'role',m.role,'name',st.name)) from app_private.site_memberships m join app_private.sites st on st.id=m.site_id where m.user_id=p_actor and m.active and st.status='active'),'[]'));
 elsif p_action='profile.save' then
 if p_actor is null then raise exception 'unauthorized' using errcode='PT401'; end if;
 insert into public.profiles(user_id,display_name) values(p_actor,btrim(p_input->>'display_name')) on conflict(user_id) do update set display_name=excluded.display_name;
 return jsonb_build_object('saved',true);
 elsif p_action like 'admin.%' then
 -- Resource-based scope overrides arbitrary client site_id, but mismatches are rejected.
 if p_action in ('admin.post.get','admin.post.published','admin.post.save','admin.post.publish','admin.post.status','admin.revisions','admin.revision.get','admin.revision.restore','admin.revision.delete') then
 select * into p from app_private.posts x where x.id=v_id for update;
 if p.id is null then raise exception 'not_found' using errcode='PT404'; end if;
 if s is not null and s<>p.site_id then raise exception 'forbidden' using errcode='PT403'; end if; s:=p.site_id;
 end if;
 perform app_private.require_member(s,p_actor);
 if p_action='admin.posts' then
 return coalesce((select jsonb_agg(x) from (select id,kind,status,draft_content->>'title' as title,lock_version,updated_at,first_published_at from app_private.posts where site_id=s order by updated_at desc limit lim offset offst) x),'[]');
 elsif p_action='admin.post.get' then return to_jsonb(p);
 elsif p_action='admin.post.published' then
 select * into u from public.post_publications pu where pu.post_id=p.id and pu.withdrawn_at is null and p.status='published';
 if u.post_id is null then return null; end if;
 select * into r from app_private.post_revisions pr where pr.id=u.revision_id and pr.post_id=p.id;
 return jsonb_build_object('revision_id',u.revision_id,'snapshot',r.snapshot,'published_at',u.published_at,'updated_at',u.updated_at);
 elsif p_action='admin.post.create' then
 insert into app_private.posts(site_id,author_id,kind,draft_content) values(s,p_actor,p_input->>'kind',coalesce(p_input->'content','{}')) returning * into p; return to_jsonb(p);
 elsif p_action='admin.post.save' then
 if p.lock_version is distinct from (p_input->>'version')::int then raise exception 'version_conflict' using errcode='PT409'; end if;
 update app_private.posts set draft_content=p_input->'content',lock_version=lock_version+1,updated_at=now() where app_private.posts.id=p.id returning * into p;
 if coalesce((p_input->>'checkpoint')::boolean,false) then
 select * into r from app_private.post_revisions pr where pr.post_id=p.id order by pr.revision_order desc limit 1;
 if r.id is null or r.snapshot is distinct from p.draft_content then
 insert into app_private.post_revisions(post_id,snapshot,created_by,reason,post_version)
 values(p.id,p.draft_content,p_actor,'checkpoint',p.lock_version);
 end if;
 end if;
 return to_jsonb(p);
 elsif p_action='admin.revisions' then
 return coalesce((select jsonb_agg(x) from (
 select pr.id,pr.created_at,pr.created_by,pr.schema_version,pr.reason,pr.post_version,
 coalesce(pr.snapshot->>'title','') as title,app_private.revision_excerpt(pr.snapshot) as excerpt,
 coalesce(pu.revision_id=pr.id,false) as is_published
 from app_private.post_revisions pr left join public.post_publications pu on pu.post_id=pr.post_id
 where pr.post_id=p.id order by pr.revision_order desc limit lim offset offst
 ) x),'[]');
 elsif p_action='admin.revision.get' then
 select * into r from app_private.post_revisions pr where pr.post_id=p.id and pr.id=(p_input->>'revision_id')::uuid;
 if r.id is null then raise exception 'not_found' using errcode='PT404'; end if;
 return jsonb_build_object('id',r.id,'created_at',r.created_at,'created_by',r.created_by,
 'schema_version',r.schema_version,'reason',r.reason,'post_version',r.post_version,
 'title',coalesce(r.snapshot->>'title',''),'excerpt',app_private.revision_excerpt(r.snapshot),
 'is_published',exists(select 1 from public.post_publications pu where pu.post_id=p.id and pu.revision_id=r.id),
 'snapshot',r.snapshot);
 elsif p_action='admin.revision.restore' then
 if p.lock_version is distinct from (p_input->>'version')::int then raise exception 'version_conflict' using errcode='PT409'; end if;
 select snapshot into d from app_private.post_revisions where post_id=p.id and app_private.post_revisions.id=(p_input->>'revision_id')::uuid;
 if not found then raise exception 'not_found' using errcode='PT404'; end if;
 if p.draft_content is distinct from d then
 select * into r from app_private.post_revisions pr where pr.post_id=p.id order by pr.revision_order desc limit 1;
 if r.id is null or r.snapshot is distinct from p.draft_content then
 insert into app_private.post_revisions(post_id,snapshot,created_by,reason,post_version)
 values(p.id,p.draft_content,p_actor,'before_restore',p.lock_version);
 end if;
 end if;
 update app_private.posts set draft_content=d,lock_version=lock_version+1,updated_at=now() where app_private.posts.id=p.id returning * into p; return to_jsonb(p);
 elsif p_action='admin.revision.delete' then
 if p.lock_version is distinct from (p_input->>'version')::int then raise exception 'version_conflict' using errcode='PT409'; end if;
 rev:=(p_input->>'revision_id')::uuid;
 if exists(select 1 from public.post_publications pu where pu.post_id=p.id and pu.revision_id=rev) then
 raise exception 'published_revision_protected' using errcode='PT409';
 end if;
 delete from app_private.post_revisions pr where pr.post_id=p.id and pr.id=rev returning pr.id into aid;
 if aid is null then raise exception 'not_found' using errcode='PT404'; end if;
 perform app_private.audit(s,p_actor,'post.revision.delete',p.id,jsonb_build_object('revision_id',rev));
 return jsonb_build_object('deleted',true);
 elsif p_action='admin.post.publish' then
 if p.lock_version is distinct from (p_input->>'version')::int then raise exception 'version_conflict' using errcode='PT409'; end if;
 perform app_private.validate_publish(p); d:=p.draft_content;
 if p.kind='article' and length(coalesce(p_input->>'rendered_html',''))=0 then raise exception 'empty_body' using errcode='PT422'; end if;
 select * into u from public.post_publications pu where pu.post_id=p.id for update;
 if u.post_id is not null and exists(select 1 from app_private.post_revisions pr where pr.id=u.revision_id and pr.snapshot=d) then
 rev:=u.revision_id;
 else
 select * into r from app_private.post_revisions pr where pr.post_id=p.id order by pr.revision_order desc limit 1;
 if r.id is not null and r.snapshot=d and r.reason='checkpoint' then
 rev:=r.id;
 update app_private.post_revisions set reason='published',post_version=p.lock_version+1 where id=rev;
 else
 insert into app_private.post_revisions(post_id,snapshot,created_by,reason,post_version)
 values(p.id,d,p_actor,'published',p.lock_version+1) returning id into rev;
 end if;
 end if;
 insert into public.post_publications(post_id,site_id,revision_id,slug,title,category_code,tags,body_html,metadata,cover_asset_id,pdf_asset_id,comments_enabled,published_at)
 values(p.id,s,rev,d->>'slug',d->>'title',d->>'category_code',array(select distinct btrim(t) from jsonb_array_elements_text(coalesce(d->'tags','[]'))t),case when p.kind='article' then p_input->>'rendered_html' end,coalesce(d->'metadata','{}'),case when p.kind='article' then (d->>'cover_asset_id')::uuid end,case when p.kind='pdf' then (d->>'pdf_asset_id')::uuid end,p.kind='article' and coalesce((d->>'comments_enabled')::boolean,true),coalesce(p.first_published_at,now()))
 on conflict(post_id) do update set revision_id=excluded.revision_id,slug=excluded.slug,title=excluded.title,category_code=excluded.category_code,tags=excluded.tags,body_html=excluded.body_html,metadata=excluded.metadata,cover_asset_id=excluded.cover_asset_id,pdf_asset_id=excluded.pdf_asset_id,comments_enabled=excluded.comments_enabled,updated_at=now(),withdrawn_at=null;
 delete from public.publication_assets where post_id=p.id;
 for aid in select distinct x::uuid from jsonb_array_elements_text(coalesce(p_input->'asset_ids','[]'))x loop
 if not exists(select 1 from app_private.media_assets where app_private.media_assets.id=aid and site_id=s and kind='image' and state='ready') then raise exception 'invalid_asset' using errcode='PT422'; end if;
 insert into public.publication_assets(post_id,asset_id,purpose) values(p.id,aid,'body') on conflict do nothing;
 end loop;
 aid:=case when p.kind='article' then (d->>'cover_asset_id')::uuid else (d->>'pdf_asset_id')::uuid end;
 insert into public.publication_assets(post_id,asset_id,purpose) values(p.id,aid,case when p.kind='article' then 'cover' else 'pdf' end) on conflict(post_id,asset_id) do update set purpose=excluded.purpose;
 if p.kind='pdf' then insert into public.publication_assets(post_id,asset_id,purpose) select p.id,preview_asset_id,'pdf-preview' from app_private.media_assets where app_private.media_assets.id=aid; end if;
 update app_private.posts set status='published',first_published_at=coalesce(first_published_at,now()),deleted_at=null,lock_version=lock_version+1,updated_at=now() where app_private.posts.id=p.id;
 perform app_private.audit(s,p_actor,'post.publish',p.id,jsonb_build_object('revision_id',rev));
 insert into app_private.outbox_jobs(site_id,type,resource_id,dedupe_key)
 values(s,'invalidate_cache',p.id,'publish:'||p.id::text||':'||(p.lock_version+1)::text);
 return jsonb_build_object('post_id',p.id,'revision_id',rev,'version',p.lock_version+1);
 elsif p_action='admin.post.status' then
 if p.lock_version is distinct from (p_input->>'version')::int then raise exception 'version_conflict' using errcode='PT409'; end if;
 key:=p_input->>'status'; if key not in ('private','trashed') or key is null then raise exception 'invalid_status' using errcode='PT422'; end if;
 update app_private.posts set status=key,deleted_at=case when key='trashed' then now() end,lock_version=lock_version+1,updated_at=now() where app_private.posts.id=p.id;
 update public.post_publications set withdrawn_at=now() where post_id=p.id;
 perform app_private.audit(s,p_actor,'post.'||key,p.id);
 insert into app_private.outbox_jobs(site_id,type,resource_id,dedupe_key) values(s,'invalidate_cache',p.id,'status:'||p.id::text||':'||(p.lock_version+1)::text);
 return jsonb_build_object('version',p.lock_version+1,'status',key);
 elsif p_action='admin.members' then
 perform app_private.require_member(s,p_actor,array['owner']);
 return coalesce((select jsonb_agg(to_jsonb(m)) from app_private.site_memberships m where site_id=s),'[]');
 elsif p_action='admin.member.set' then
 -- Acquire site lock before changing owner rows; serializes concurrent owner removals.
 perform 1 from app_private.sites where app_private.sites.id=s for update;
 perform app_private.require_member(s,p_actor,array['owner']); target:=(p_input->>'user_id')::uuid;
 role_name:=p_input->>'role'; b:=coalesce((p_input->>'active')::boolean,true);
 insert into app_private.site_memberships(site_id,user_id,role,active,granted_by) values(s,target,role_name,b,p_actor)
 on conflict(site_id,user_id) do update set role=excluded.role,active=excluded.active,granted_by=p_actor,updated_at=now();
 perform app_private.audit(s,p_actor,'member.set',target,jsonb_build_object('role',role_name,'active',b)); return jsonb_build_object('saved',true);
 elsif p_action in ('admin.settings.get','admin.settings.save','admin.settings.apply') then
 select * into st from app_private.sites where app_private.sites.id=s for update;
 if p_action='admin.settings.get' then return jsonb_build_object('draft',st.draft_settings,'published',st.published_settings,'version',st.settings_version); end if;
 if st.settings_version is distinct from (p_input->>'version')::int then raise exception 'version_conflict' using errcode='PT409'; end if;
 d:=case when p_action='admin.settings.save' then p_input->'settings' else st.draft_settings end; perform app_private.check_settings(s,d);
 update app_private.sites set draft_settings=d,published_settings=case when p_action='admin.settings.apply' then d else published_settings end,settings_version=settings_version+1,settings_updated_at=now() where app_private.sites.id=s;
 perform app_private.audit(s,p_actor,p_action,s); return jsonb_build_object('version',st.settings_version+1);
 elsif p_action='admin.comments' then
 return coalesce((select jsonb_agg(x) from (select c.id,c.post_id,c.parent_id,c.body,c.status,c.version,c.created_at,c.author_kind,coalesce(pr.display_name,c.guest_name,'독자') as display_name from public.comments c join app_private.posts p on p.id=c.post_id left join public.profiles pr on pr.user_id=c.author_id where p.site_id=s order by c.created_at desc limit lim offset offst)x),'[]');
 elsif p_action='admin.comment.moderate' then
 select c0.* into c from public.comments c0 join app_private.posts p0 on p0.id=c0.post_id where c0.id=v_id and p0.site_id=s for update of c0;
 if c.id is null then raise exception 'not_found' using errcode='PT404'; end if;
 if c.version is distinct from (p_input->>'version')::int then raise exception 'version_conflict' using errcode='PT409'; end if;
 key:=p_input->>'status'; if key is null or key not in ('visible','hidden','deleted') or c.status='deleted' then raise exception 'invalid_status' using errcode='PT422'; end if;
 update public.comments set status=key,body=case when key='deleted' then '' else body end,version=version+1,updated_at=now(),deleted_at=case when key='deleted' then now() end where public.comments.id=c.id;
 perform app_private.audit(s,p_actor,'comment.'||key,c.id); return jsonb_build_object('version',c.version+1);
 elsif p_action='admin.reports' then
 return coalesce((select jsonb_agg(x) from (select r.* from app_private.comment_reports r join public.comments c on c.id=r.comment_id join app_private.posts p on p.id=c.post_id where p.site_id=s order by r.created_at desc limit lim offset offst)x),'[]');
 elsif p_action='admin.report.resolve' then
 key:=p_input->>'status'; if key is null or key not in ('resolved','dismissed') then raise exception 'invalid_status' using errcode='PT422'; end if;
 update app_private.comment_reports r set status=key from public.comments c,app_private.posts p where r.id=v_id and c.id=r.comment_id and p.id=c.post_id and p.site_id=s;
 if not found then raise exception 'not_found' using errcode='PT404'; end if;
 perform app_private.audit(s,p_actor,'report.'||key,v_id); return jsonb_build_object('saved',true);
 elsif p_action='admin.audit' then
 perform app_private.require_member(s,p_actor,array['owner','admin']);
 return coalesce((select jsonb_agg(x) from (select * from app_private.audit_events where site_id=s order by created_at desc limit lim offset offst)x),'[]');
 end if;
 elsif p_action='comment.create' then
 select * into p from app_private.posts x where x.id=v_id for share;
 if p.id is null or not app_private.is_public(p.id) or p.kind<>'article' or not (select comments_enabled from public.post_publications where post_id=p.id) then raise exception 'comments_unavailable' using errcode='PT403'; end if;
 if p_actor is not null then actorhash:='user:'||p_actor::text; elsif length(coalesce(actorhash,''))<32 then raise exception 'visitor_required' using errcode='PT401'; end if;
 if nullif(p_input->>'parent_id','') is not null and not exists(select 1 from public.comments where public.comments.id=(p_input->>'parent_id')::uuid and post_id=p.id and parent_id is null and status='visible') then raise exception 'invalid_reply' using errcode='PT422'; end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p.id::text||actorhash||(p_input->>'request_key'),0));
 select * into c from public.comments where post_id=p.id and request_actor_hash=actorhash and request_key=(p_input->>'request_key')::uuid;
 if c.id is not null then
 if c.request_hash is distinct from p_input->>'request_hash' then raise exception 'idempotency_conflict' using errcode='PT409'; end if;
 return jsonb_build_object('id',c.id,'version',c.version,'duplicate',true);
 end if;
 insert into public.comments(post_id,author_id,author_kind,guest_name,parent_id,body,request_key,request_actor_hash,request_hash)
 values(p.id,p_actor,case when p_actor is null then 'guest' else 'member' end,case when p_actor is null then p_input->>'guest_name' end,nullif(p_input->>'parent_id','')::uuid,btrim(p_input->>'body'),(p_input->>'request_key')::uuid,actorhash,p_input->>'request_hash') returning * into c;
 if p_actor is null then insert into app_private.comment_credentials(comment_id,password_hash) values(c.id,p_input->>'password_hash'); end if;
 return jsonb_build_object('id',c.id,'version',c.version,'duplicate',false);
 elsif p_action='comment.credential' then
 -- Internal only: Edge verifies Argon2 before forwarding a mutation. Not a client action.
 select c0.* into c from public.comments c0 where c0.id=v_id;
 if c.id is null or not app_private.is_public(c.post_id) or c.author_kind<>'guest' or c.status='deleted' then raise exception 'not_found' using errcode='PT404'; end if;
 return (select jsonb_build_object('password_hash',password_hash) from app_private.comment_credentials where comment_id=v_id);
 elsif p_action in ('comment.edit','comment.delete') then
 select * into c from public.comments c0 where c0.id=v_id for update;
 if c.id is null or not app_private.is_public(c.post_id) or c.status='deleted' then raise exception 'not_found' using errcode='PT404'; end if;
 if not ((c.author_kind='member' and c.author_id=p_actor) or (c.author_kind='guest' and coalesce((p_input->>'guest_verified')::boolean,false))) then raise exception 'forbidden' using errcode='PT403'; end if;
 if c.version is distinct from (p_input->>'version')::int then raise exception 'version_conflict' using errcode='PT409'; end if;
 update public.comments set body=case when p_action='comment.delete' then '' else btrim(p_input->>'body') end,status=case when p_action='comment.delete' then 'deleted' when status='hidden' then 'hidden' else 'visible' end,version=version+1,updated_at=now(),deleted_at=case when p_action='comment.delete' then now() end where public.comments.id=c.id;
 return jsonb_build_object('id',c.id,'version',c.version+1);
 elsif p_action='comment.report' then
 if p_actor is null then raise exception 'unauthorized' using errcode='PT401'; end if;
 select * into c from public.comments c0 where c0.id=v_id;
 if c.id is null or c.status<>'visible' or not app_private.is_public(c.post_id) then raise exception 'not_found' using errcode='PT404'; end if;
 insert into app_private.comment_reports(comment_id,reporter_id,reason) values(v_id,p_actor,p_input->>'reason') on conflict(comment_id,reporter_id) do nothing;
 return jsonb_build_object('reported',true);
 elsif p_action='like.set' then
 select * into p from app_private.posts p0 where p0.id=v_id for share;
 if p.id is null or not app_private.is_public(p.id) or p.kind<>'article' then raise exception 'reactions_unavailable' using errcode='PT403'; end if;
 if p_actor is null and length(coalesce(actorhash,''))<32 then raise exception 'visitor_required' using errcode='PT401'; end if;
 b:=(p_input->>'liked')::boolean; if b is null then raise exception 'invalid_input' using errcode='PT422'; end if;
 if b then insert into app_private.post_likes(post_id,user_id,visitor_hash) values(v_id,p_actor,case when p_actor is null then actorhash end) on conflict do nothing;
 else delete from app_private.post_likes where post_id=v_id and ((p_actor is not null and user_id=p_actor) or (p_actor is null and visitor_hash=actorhash)); end if;
 return jsonb_build_object('liked',b,'count',(select count(*) from app_private.post_likes where post_id=v_id));
 elsif p_action='asset.create' then
 perform app_private.require_member(s,p_actor);
 key:=p_input->>'kind'; if key is null or key not in ('image','pdf') then raise exception 'invalid_kind' using errcode='PT422'; end if;
 aid:=gen_random_uuid();
 insert into app_private.media_assets(id,site_id,owner_id,kind,bucket,object_path) values(aid,s,p_actor,key,case when key='pdf' then 'documents-private' else 'originals-private' end,s::text||'/'||aid::text||'/original') returning * into a;
 return to_jsonb(a);
 elsif p_action in ('asset.internal','asset.complete','asset.access') then
 select * into a from app_private.media_assets a0 where a0.id=v_id;
 if a.id is null then raise exception 'not_found' using errcode='PT404'; end if;
 if s is not null and s<>a.site_id then raise exception 'forbidden' using errcode='PT403'; end if;
 if p_action<>'asset.access' or not (a.state='ready' and exists(select 1 from app_private.sites where app_private.sites.id=a.site_id and status='active') and (exists(select 1 from public.publication_assets pa where pa.asset_id=a.id and app_private.is_public(pa.post_id)) or exists(select 1 from app_private.sites where app_private.sites.id=a.site_id and published_settings->>'hero_asset_id'=a.id::text))) then perform app_private.require_member(a.site_id,p_actor); end if;
 if p_action='asset.complete' then
 if a.state<>'uploading' and a.state<>'failed' then return to_jsonb(a); end if;
 update app_private.media_assets set state='processing',metadata=p_input->'metadata' where app_private.media_assets.id=a.id returning * into a;
 insert into app_private.outbox_jobs(site_id,type,resource_id,dedupe_key) values(a.site_id,'process_asset',a.id,'process:'||a.id::text) on conflict(site_id,dedupe_key) do update set status='queued',next_run_at=now(),lease_until=null;
 end if;
 return to_jsonb(a);
 end if;
 raise exception 'unknown_action' using errcode='PT400';
end $$;

revoke all on function public.travel_api(text,uuid,jsonb) from public,anon,authenticated;
grant execute on function public.travel_api(text,uuid,jsonb) to service_role;
